# Generated by Django 4.0 on 2021-12-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occupancy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('occupancy', models.BooleanField(default=False)),
            ],
        ),
    ]
